Added a WKWebView based example
jivesoftware/JiveAuthenticatingHTTPProtocol pull request #10
Opened 2018-07-30 14:51 UTC by dodikk

WKWebView does not need this POD to achieve the same thing.
Still, I think the example and a readme mention might be useful.

Based on https://github.com/jivesoftware/JiveAuthenticatingHTTPProtocol/pull/9
After merging that one, the diffs should become more brief.

2018-07-30 15:31 UTC, dodikk commented
The "foo/bar" example with basic authorization works fine in WKWebView.
However, my "video with authorization" example fails (while it works fine with `UIWebView` and this library).

I'll push more commits when I discover the correct settings for `WKWebView`.

2018-07-30 16:44 UTC, dodikk commented
Using an isolated non-persistent site data store pops up the alert for NTLM but that does not help the playback yet.

```obj-c
WKWebViewConfiguration* config = [WKWebViewConfiguration new];
    config.allowsInlineMediaPlayback = YES;
    config.allowsPictureInPictureMediaPlayback = NO;
    config.mediaTypesRequiringUserActionForPlayback = WKAudiovisualMediaTypeAll;
    config.websiteDataStore = [WKWebsiteDataStore nonPersistentDataStore];
```

2018-07-31 08:36 UTC, dodikk commented
> Using an isolated non-persistent site data store pops up the alert for NTLM but that does not help the playback yet.

Never mind, the video's URL scheme was `http` which is "banned" by default due to Apple security policy. So that the exceptions should be added explicitly.

2018-08-02 03:18 UTC, hborders requested changes
Very minor request.

2018-08-02 03:18 UTC, hborders commented on JiveAuthenticatingHTTPProtocolDemo/WKWebViewDemo/ViewController.m
> +#pragma mark - JAHPAuthenticatingHTTPProtocolDelegate
I don't think you should bring `JAHPAuthenticatingHTTPProtocolDelegate` into this at all. It isn't needed.

2018-08-02 10:10 UTC, dodikk commented on JiveAuthenticatingHTTPProtocolDemo/WKWebViewDemo/ViewController.m
> +#pragma mark - JAHPAuthenticatingHTTPProtocolDelegate
Deleted the mentioned `#pragma mark`

2018-08-03 08:44 UTC, dodikk commented
Will be merged as part of a more recent PR https://github.com/jivesoftware/JiveAuthenticatingHTTPProtocol/pull/11

2018-08-03 08:44 UTC, closed without merging