[memoization] fix incorrect credentials asynchronous loop
jivesoftware/JiveAuthenticatingHTTPProtocol pull request #11
Opened 2018-08-01 10:01 UTC by dodikk

Based on https://github.com/jivesoftware/JiveAuthenticatingHTTPProtocol/pull/10

Fixed an issue for the case when wrong credentials are entered by the user.
My memoization fix https://github.com/jivesoftware/JiveAuthenticatingHTTPProtocol/pull/9 has caused it.

The issue has been fixed for both the existing `UIWebView` based demo and for the `WKWebView` one.

### Issue description
The page would not end up loading since wrong credentials will constantly be provided to the authentication challenge callback. For this reason, the credentials alert would not show up (since the credentials have been memoized but they are wrong).

### The fix

1. Fixed the condition for supplying the memoized credentials

```obj-c
-(BOOL)isUserInputCredentialsMemoized {
    
    BOOL hasInput = (nil != self.userInput);
    BOOL result = hasInput && self.isUserInputAcceptedByServer;
    
    return result;
}
```

2. Marking credentials as "valid" in `webViewDidFinishLoad:`
If not marked, the alert will show up all over again until cancelled by the user (as it had before).

2018-08-02 03:21 UTC, hborders requested changes

2018-08-02 03:21 UTC, hborders commented on JiveAuthenticatingHTTPProtocolDemo/WKWebViewDemo/ViewController.m
> +#pragma mark - JAHPAuthenticatingHTTPProtocolDelegate
Same issue as before. I don't think we should mention `JAHPAuthenticatingHTTPProtocolDelegate` in this implementation because it isn't needed. I think it'll only confuse people.

2018-08-02 20:34 UTC, hborders approved these changes
Ok. This looks good. Are you ready to merge?

2018-08-02 20:34 UTC, hborders commented
It seems like this is a combination of the other two PRs, so maybe you should close them?

2018-08-03 08:44 UTC, dodikk commented
> It seems like this is a combination of the other two PRs, so maybe you should close them?

Indeed, it has a few commits on top of those previous ones as I've mentioned in the description. They will be automatically closed by github when this one gets merged.
I'll close them manually anyway as long as you've requested that.

2018-08-03 13:57 UTC, merged